In [44]:
import numpy as np
import pandas as pd

# read the data
column_list_ratings = ["UserID", "MovieID", "Ratings", "Timestamp"]
ratings_data = pd.read_csv('ratings.dat', sep='::', names = column_list_ratings, engine='python')
column_list_movies = ["MovieID", "Title", "Genre"]
movies_data = pd.read_csv("movies.dat", sep='::', names = column_list_movies, engine='python', encoding='latin')
column_list_users = ["UserID", "gender", "Age", "Occupation", "Zixp-code"]
user_data = pd.read_csv("users.dat", sep='::', names = column_list_users, engine='python')



nr_users = np.max(ratings_data.UserID.values)
nr_movies = np.max(ratings_data.MovieID.values)
ratings_matrix = np.ndarray(shape=(nr_users, nr_movies),dtype=np.uint8)

ratings_matrix[ratings_data.UserID.values - 1, ratings_data.MovieID.values - 1] = ratings_data.Ratings.values
ratings_matrix

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [45]:
ratings_matrix = (ratings_matrix - ratings_matrix.mean(axis = 0))/ratings_matrix.std(axis = 0) #normalize the data
ratings_matrix[np.isnan(ratings_matrix)] = 0 #replace nan values with 0.
ratings_matrix.shape


C:\Users\nkulh\AppData\Local\Temp\ipykernel_23292\1555921688.py:1: RuntimeWarning: invalid value encountered in true_divide
  ratings_matrix = (ratings_matrix - ratings_matrix.mean(axis = 0))/ratings_matrix.std(axis = 0) #normalize the data


(6040, 3952)

In [49]:
from numpy.linalg import eig

#Getting the ratings matrix to a variable A
A=ratings_matrix
print("The shape of ratings matrix:  ",A.shape)
print("The original matrix:  \n",A)


U,S,VT=np.linalg.svd(A)
print('U matrix shape:  ',U.shape)
print('S matrix shape:  ',S.shape)
print('VT matrix shape:  ',VT.shape)

The shape of ratings matrix:   (6040, 3952)
The original matrix:  
 [[ 1.7587341  -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 ...
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [ 0.77455344 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]]
U matrix shape:   (6040, 6040)
S matrix shape:   (3952,)
VT matrix shape:   (3952, 3952)


In [50]:
E = np.zeros((A.shape[0], A.shape[1]))

# Convert Sigma to diagonal matrix
E[:A.shape[1], :A.shape[1]] = np.diag(S)
E.shape
B=np.matmul(U,E)
C=np.matmul(B,VT)
print(C)


[[ 1.7587341  -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 ...
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [ 0.77455344 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]]


In [51]:
print('The shape of U matrix is: ',U.shape)
print('The shape of E matrix is: ',E.shape)
print('The shape of VT matrix is: ',VT.shape)

The shape of U matrix is:  (6040, 6040)
The shape of E matrix is:  (6040, 3952)
The shape of VT matrix is:  (3952, 3952)


In [75]:
from numpy.linalg import eig

#Getting the ratings matrix to a variable A
A=ratings_matrix
print("The shape of ratings matrix:  ",A.shape)
print("The original matrix:  \n",A)


U,S,VT=np.linalg.svd(A)
print('U matrix shape:  ',U.shape)
print('S matrix shape:  ',S.shape)
print('VT matrix shape:  ',VT.shape)


# In[347]:


E = np.zeros((A.shape[0], A.shape[1]))

# Convert Sigma to diagonal matrix
E[:A.shape[1], :A.shape[1]] = np.diag(S)
E.shape
B=np.matmul(U,E)
C=np.matmul(B,VT)
print(C)


# In[90]:


# Print the shapes
print('The shape of U matrix is: ',U.shape)
print('The shape of E matrix is: ',E.shape)
print('The shape of VT matrix is: ',VT.shape)


The shape of ratings matrix:   (6040, 3952)
The original matrix:  
 [[ 1.7587341  -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 ...
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [ 0.77455344 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]]
U matrix shape:   (6040, 6040)
S matrix shape:   (3952,)
VT matrix shape:   (3952, 3952)
[[ 1.7587341  -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 ...
 [-0.70171755 -0.34446173 -0.27495584 ... -0.09136796 -0.07885485
  -0.25386356]
 [-0.70171755 -0.34446

In [76]:
k=[100,1000,2000,3000]

#Constructing lower rank prediction matrices
for i in range(len(k)):
    Rk=U[:,:k[i]]@np.diag(S[:k[i]])@VT[:k[i],:]
    if (i==0):
        R100=Rk
    elif i==1:
        R1000=Rk
    elif i==2:
        R2000=Rk
    elif i==3:
        R3000=Rk
print(matrix_rank(R100),matrix_rank(R1000),matrix_rank(R2000),matrix_rank(R3000))

NameError: name 'matrix_rank' is not defined

In [59]:
user = [11,22,33]
for i in user:
    print(R100[i][1376])

-0.4591952956371597
0.3671136096473012
-0.04121511796267103


In [64]:
user = [11,22,33]
for i in user:
    print(R1000[i][1376])
RT=R1000.T
print(R1000.shape,RT.shape)    
Y=RT[1376][:]
print(Y)


# In[350]:


num=RT.dot(Y)
print(num)


# In[351]:


den=s.norm(Y)*la.norm(RT)
print(den)


# In[352]:


cos=num/den
print(cos)


# In[353]:


index=np.argsort(-cos)
print(index)

movie_titles = movies_data["Title"].tolist()
for i in index:
    print(movie_titles[i])

-0.4666582627416219
-0.2838819313053366
-0.5003560629246577
(6040, 3952) (3952, 6040)
[-0.53173769  0.16743401 -0.18018232 ... -0.56064447 -0.6354071
 -1.38147735]
[1654.58160537 2076.90576819 1356.58315134 ...  216.09394659   53.03458232
  484.00441761]


AttributeError: 'numpy.ndarray' object has no attribute 'norm'

In [26]:
# Movie id as given in question
movie_id = 1377

# Extracting user_id for the given movie_id
user_ids_1377 = ratings_data[ratings_data['MovieID'] == movie_id]['UserID'].head(3).values

movie_idx = np.where(movie_ids == movie_id)[0][0]

# Printing the rating given by every user to the movie
for user_1 in user_ids_1377:
    ratings_1377 = ratings_matrix[user_1-1, movie_idx]
    print("User",user_1, "Rated the movie: ",ratings_1377 )

User 10 Rated the movie:  3
User 13 Rated the movie:  3
User 18 Rated the movie:  2


In [61]:
# Compute column averages
means = np.sum(ratings_matrix, axis=0) / np.count_nonzero(ratings_matrix, axis=0)

# Replace missing ratings with column means
filled_ratings_matrix = np.where(ratings_matrix == 0, means[np.newaxis, :], ratings_matrix)

# Subtract column means from ratings matrix
mean_centered_ratings_matrix = filled_ratings_matrix - means[np.newaxis, :]

mean_centered_ratings_matrix

C:\Users\nkulh\AppData\Local\Temp\ipykernel_23292\3795815596.py:2: RuntimeWarning: invalid value encountered in true_divide
  means = np.sum(ratings_matrix, axis=0) / np.count_nonzero(ratings_matrix, axis=0)


array([[ 1.7587341 , -0.34446173, -0.27495584, ..., -0.09136796,
        -0.07885485, -0.25386356],
       [-0.70171755, -0.34446173, -0.27495584, ..., -0.09136796,
        -0.07885485, -0.25386356],
       [-0.70171755, -0.34446173, -0.27495584, ..., -0.09136796,
        -0.07885485, -0.25386356],
       ...,
       [-0.70171755, -0.34446173, -0.27495584, ..., -0.09136796,
        -0.07885485, -0.25386356],
       [-0.70171755, -0.34446173, -0.27495584, ..., -0.09136796,
        -0.07885485, -0.25386356],
       [ 0.77455344, -0.34446173, -0.27495584, ..., -0.09136796,
        -0.07885485, -0.25386356]])

In [32]:
# Calculate mean by movie
mean_ratings = np.zeros((num_movies,))
for j in range(num_movies):
    idx = np.where(ratings_matrix[:, j] != 0)
    mean_ratings[j] = np.mean(ratings_matrix[idx, j])
    
# Replace missing values with the mean rating for the given movie
for i in range(num_users):
    for j in range(num_movies):
        if ratings_matrix[i, j] == 0:
            ratings_matrix[i, j] = mean_ratings[j]
            
# Subtract mean from original ratings and divide it by the standard deviation
std_ratings = np.zeros((num_users, num_movies))
for j in range(num_movies):
    idx = np.where(ratings_matrix[:, j] != 0)
    std_ratings[idx, j] = (ratings_matrix[idx, j] - mean_ratings[j]) / np.std(ratings_matrix[idx, j])
    
# Replace NaN values with 0
std_ratings = np.nan_to_num(std_ratings, nan=0)
std_ratings

C:\Users\nkulh\AppData\Local\Temp\ipykernel_23292\2091174920.py:17: RuntimeWarning: invalid value encountered in true_divide
  std_ratings[idx, j] = (ratings_matrix[idx, j] - mean_ratings[j]) / np.std(ratings_matrix[idx, j])


array([[ 1.94297337, -0.1229419 , -3.53765168, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.94297337, -0.1229419 , -0.05648255, ...,  0.        ,
         0.        ,  0.        ],
       [-0.24404846, -0.1229419 , -0.05648255, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.24404846, -0.1229419 , -0.05648255, ...,  0.        ,
         0.        ,  0.        ],
       [-0.24404846, -0.1229419 , -0.05648255, ...,  0.        ,
         0.        ,  0.        ],
       [-0.24404846, -0.1229419 , -0.05648255, ...,  0.        ,
         0.        ,  0.        ]])

In [29]:
# Compute the SVD of the normalised matrix
u, s, vh = np.linalg.svd(std_ratings)

# Print the shapes
print("U shape: ", u.shape)
print("S shape: ", s.shape)
print("V shape: ", vh.shape)

U shape:  (6040, 6040)
S shape:  (3706,)
V shape:  (3706, 3706)


In [41]:
# Define the k values
k_values = [100, 1000, 2000, 3000]

# Loop over the k values
for k in k_values:
    # Reconstruct the rank-k matrix
    R_k = u[:, :k] @ np.diag(s[:k]) @ vh[:k, :]
    if k==1000:
        Rk_1000 = R_k
    # Make predictions for the selected users and movie
    for user_id in user_ids_1377:
        user_idx = user_id - 1
        movie_idx = 1376  # index starts from 0
        
        # Get the original rating
        rating_original = ratings_data[(ratings_data["UserID"] == user_id) & 
                                        (ratings_data["MovieID"] == 1377)]["Ratings"].values[0]
        
        # Get the predicted rating
        rating_predicted = R_k[user_idx, movie_idx]
        
        # Print the original and predicted ratings
        print("For k = {}, User {}'s original rating: {}, predicted rating: {:.2f}".format(k, user_id, rating_original, rating_predicted))


For k = 100, User 10's original rating: 3, predicted rating: -0.63
For k = 100, User 13's original rating: 3, predicted rating: -0.67
For k = 100, User 18's original rating: 2, predicted rating: -1.21
For k = 1000, User 10's original rating: 3, predicted rating: -0.11
For k = 1000, User 13's original rating: 3, predicted rating: -0.67
For k = 1000, User 18's original rating: 2, predicted rating: -1.25
For k = 2000, User 10's original rating: 3, predicted rating: -0.47
For k = 2000, User 13's original rating: 3, predicted rating: -0.73
For k = 2000, User 18's original rating: 2, predicted rating: -0.88
For k = 3000, User 10's original rating: 3, predicted rating: -0.68
For k = 3000, User 13's original rating: 3, predicted rating: -0.71
For k = 3000, User 18's original rating: 2, predicted rating: -0.76


In [62]:
def top_movie_similarity(data, movie_id, top_n=5):
    # Get the column index for the given movie_id
    movie_idx = movie_id - 1
    
    # Get the column vector for the given movie
    movie_vec = data[:, movie_idx]
    
    # Calculate the cosine similarity between the given movie and all other movies
    sim_scores = np.nan_to_num(np.dot(data.T, movie_vec) / (np.linalg.norm(data, axis=0) * np.linalg.norm(movie_vec)))
    
    # Sort the movies based on their similarity with the given movie
    top_indices = np.argsort(-sim_scores)[:top_n]
    top_scores = sim_scores[top_indices]
    
    return top_indices, top_scores

def print_similar_movies(movie_titles, top_indices):
    print('Most Similar movies: ')
    for i, idx in enumerate(top_indices):
        print(f'{i+1}. {movie_titles[idx]}')
    
# Find the top 5 similar movies for Batman Returns
movie_id = 1377
top_indices, top_scores = top_movie_similarity(Rk, movie_id, top_n=5)

movie_titles = movies_data["Title"].tolist()

# Print the top 5 similar movies
print_similar_movies(movie_titles, top_indices)

C:\Users\nkulh\AppData\Local\Temp\ipykernel_23292\3746986766.py:9: RuntimeWarning: invalid value encountered in true_divide
  sim_scores = np.nan_to_num(np.dot(data.T, movie_vec) / (np.linalg.norm(data, axis=0) * np.linalg.norm(movie_vec)))


NameError: name 'movie_titles' is not defined

In [ ]:
de top_user_similarity(data, user_id, top_n=1):
    user_idx = user_id-1
    
    user_vec = data[user_idx,:]
    
    sim_score = np.nan_to_num(np.dot(data,user_vec)/(np.linalg.norm(data,axis=0)*np.linalg.norm(user_vec)))
    
    top_idices = np.argsort(-sim_scores)[:top_n]
    top_scores = sim_scores[top_indices]
    return top_indices, top_scores

def print_similar_movies(movie_titles, top_indices):
    print('Most Similar movies: ')
    for i, idx in enumerate(top_indices):
        print(f'{i+1}. {movie_titles[idx]}')
        
user_id = 5954
top_indices, top_scores = top_movie_similarity(Rk_1000, user_id, top_n=1)

# Print the top 5 similar movies
print_similar_movies(movie_titles, top_indices)